//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_agency_Mukhtatenkov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class recruitment_agencyEntities : DbContext
    {
        private static recruitment_agencyEntities _context;
        public static recruitment_agencyEntities GetContext()
        {
            if (_context == null)
                _context = new recruitment_agencyEntities();
            return _context;
        }
        public recruitment_agencyEntities()
            : base("name=recruitment_agencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sobesedovanie> sobesedovanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
    }
}
