//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_agency_Mukhtatenkov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resume()
        {
            this.sobesedovanie = new HashSet<sobesedovanie>();
        }
    
        public int IDResume { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public string DadsName { get; set; }
        public string Education { get; set; }
        public string PhoneNumber { get; set; }
        public string Proficiences { get; set; }
        public string Mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sobesedovanie> sobesedovanie { get; set; }
    }
}
