//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_agency_Mukhtatenkov
{
    using System;
    using System.Collections.Generic;
    
    public partial class sobesedovanie
    {
        public int ID { get; set; }
        public Nullable<int> Resume { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Resume Resume1 { get; set; }
        public virtual Vacancies Vacancies { get; set; }
    }
}
